### ISSUE TITLE
每次一用就报错？6.0有兼容吗？

### ISSUE THREAD

**Issue by DearZack** [JeasonWong/Particle#1]
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zjipst.zhouxiong.testapp/com.zjipst.zhouxiong.testapp.ui.activity.StartActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2444)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:150)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)
                                                                        Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                                           at android.animation.PropertyValuesHolder.setObjectValues(PropertyValuesHolder.java:638)
                                                                           at android.animation.PropertyValuesHolder.ofObject(PropertyValuesHolder.java:398)
                                                                           at android.animation.ValueAnimator.setObjectValues(ValueAnimator.java:480)
                                                                           at android.animation.ValueAnimator.ofObject(ValueAnimator.java:396)
                                                                           at me.wangyuwei.particleview.ParticleView.startParticleAnim(ParticleView.java:196)
                                                                           at me.wangyuwei.particleview.ParticleView.startAnim(ParticleView.java:292)
                                                                           at com.zjipst.zhouxiong.testapp.ui.activity.StartActivity.onCreate(StartActivity.java:22)
                                                                           at android.app.Activity.performCreate(Activity.java:6323)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504) 
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:150) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5546) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682) 
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                                           at android.animation.PropertyValuesHolder.setObjectValues(PropertyValuesHolder.java:638)
                                                                           at android.animation.PropertyValuesHolder.ofObject(PropertyValuesHolder.java:398)
                                                                           at android.animation.ValueAnimator.setObjectValues(ValueAnimator.java:480)
                                                                           at android.animation.ValueAnimator.ofObject(ValueAnimator.java:396)
                                                                           at me.wangyuwei.particleview.ParticleView.startParticleAnim(ParticleView.java:196)
                                                                           at me.wangyuwei.particleview.ParticleView.startAnim(ParticleView.java:292)
                                                                           at com.zjipst.zhouxiong.testapp.ui.activity.StartActivity.onCreate(StartActivity.java:22)
                                                                           at android.app.Activity.performCreate(Activity.java:6323)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:150)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
                                                                        at com.andro`

**Comment by JeasonWong** [comment]
能贴一下你的使用方式吗？（这个和6.0应该是没有关系的）

**Comment by DearZack** [comment]
`particleView = (ParticleView) findViewById(R.id.particle_view);

```
    particleView.startAnim();

    particleView.setOnParticleAnimListener(new ParticleView.ParticleAnimListener() {
        @Override
        public void onAnimationEnd() {
            Toast.makeText(StartActivity.this, "Animation is End", Toast.LENGTH_SHORT).show();
            Intent intent = new Intent(StartActivity.this, MainActivity.class);
            startActivity(intent);
            finish();
        }
    });`
```

**Comment by JeasonWong** [comment]
fix了，谢谢指出！

``` gradle
compile 'me.wangyuwei:ParticleView:1.0.1'
```
